version: "3.9"

services:

  api:
    build: ./
    environment:
      ADDR: '0.0.0.0'
      PORT: 8000
      ENV: 'local'
    volumes:
      - ./:/
    ports:
      - 8000:8000
    restart: always
    # command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --workers 6 --reload"
    command: bash -c "python3 main.py"
